name: Build and Push Docker
on: [push]
jobs:
  build:
    runs-on: node:20
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/multiThreadApp         
          file: ./src/multiThreadApp/Dockerfile  
          push: true
          tags: cr7siiuuu/web:1.0.4
