name: Build and Push Docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image multi-arch
        uses: docker/build-push-action@v3
        with:
          context: ./src/multiThreadApp
          file: ./src/multiThreadApp/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cr7siiuuu/web:1.0.7
